name: assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  font_awesome_flutter: ^10.5.0
  fan_carousel_image_slider:
  flutter_pannable_rating_bar: ^2.7.2+1
  sliding_clipped_nav_bar: ^3.1.0+4  
  google_fonts: ^5.1.0
  fluttertoast: ^8.2.2
  flutter_staggered_grid_view: ^0.7.0   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/contact_list/
    - assets/Fruits/
    - assets/avatar.png
    - assets/farmerfresh/
    - assets/farmerfresh/categoryimages/
